language: python

services:
  - docker

before_install:
  - docker-compose up -d
  - docker exec -it coms-novnc-1 make -f /root/catkin_ws/src/Makefile check-health

script:
  - docker exec -it coms-novnc-1 make -f /root/catkin_ws/src/Makefile test

