language: python

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker exec -it "$(docker ps -aqf 'name=coms*')" make -f /root/catkin_ws/src/Makefile check-health

script:
  - docker exec -it "$(docker ps -aqf 'name=coms*')" make -f /root/catkin_ws/src/Makefile test coverage
