BROADCAST_INTERVAL = 3      # Period of seconds for network scan
DISCOVERABLE_TIMEOUT = 0.5  # Period of seconds to wait for nearby devices
IP_RANGE = 10               # From xxx.xxx.xxx.0 -> xxx.xxx.xxx.10
RESPONSE_TIMEOUT = 3        # Number of seconds to stop waiting for a response
PACKET_BUFFER_SIZE = 4096   # Number of bytes for sockets to send and recieve at once
ENCODING = 'UTF-8'          # Used for encoding and decoding byte strings
MAX_CLIENTS = 5             # Max number of broadcasters a listener can service at one time
EXACT_MAP_SIZE = 2555904    # The exact size (in bytes) of an occupancy grid map
POSSIBLE_IPS = ["192.168.0." + str(ip) for ip in range(IP_RANGE+1)]
ACK = b'ack'
NACK = b'nck'
